Object.end;
Object.myCodeMirrorInstance;
Object.join;
Object.sep;
Object.request;
Object.get;
Object.index;
Object.exec;
Object.write;
Object.out;
Object.out.println;
Object.resolve;
Object.error;
Object.error.println;
Object.on;
HTMLDocument.prototype.getElementById;
var cljs;
cljs.user;
Function.prototype.isArray;
Function.prototype.iterator;
Function.prototype.fromCharCode;
Function.prototype.MAX_VALUE;
var Buffer;
Buffer.byteLength;
goog.dependencies_;
goog.dependencies_.nameToPath;
goog.dependencies_.visited;
goog.dependencies_.written;
goog.basePath;
goog.require_figwheel_backup_;
goog.require;
goog.net;
goog.net.XhrIo;
goog.net.XhrIo.send;
goog.require__;
goog.string;
goog.string.StringBuffer;
goog.string.StringBuffer.prototype.append;
goog.string.StringBuffer.prototype.getLength;
goog.isProvided_;
goog.cljsReloadAll_;
var process;
process.hrtime;
JSON.parse;
var require;
require.cache;
var figwheel;
figwheel.core;
figwheel.core.logger;
var Java;
Java.type;
